### ISSUE TITLE
Simplify object modification

### ISSUE THREAD

**Issue by bcalou** [mathisang/spaceGame#10]
+1 pour la grosse amélioration du code depuis la dernière fois, continuez comme ça.

Vous pouvez simplifier le code suivant :

```
Object.assign(updatedGauge, {
            [type]:
              gauge[type] +
              cards[card].card.responses[idButton - 1].impacts[type],
          }
```

en la forme beaucoup plus courante : 

```
updatedGauge[type] = gauge[type] + cards[card].card.responses[idButton - 1].impacts[type]
```

**Comment by mathisang** [comment]
Merci, votre aide m'a bien avancé !
C'est fait, merci.
https://github.com/mathisang/spaceGame/commit/ba2e1077332abe0f8dbaf0f68113042e2395c1ee
