### ISSUE TITLE
Expliciter les comparaisons

### ISSUE THREAD

**Issue by bcalou** [mathisang/spaceGame#11]
Puisqu'on a le luxe d'aller dans le détail, ce genre de code est très obscur :+1: 

```
e === (1 || 2)
```

Quelqu'un qui débarque ne peut pas comprendre.

Il faut renommer le paramètre e pour lui donner un nom compréhensible.
Il faut utiliser des constantes pour stocker 1 & 2.

Exemple :

```
const FAIL = 1;
const SUCCESS = 2;

...

result === (FAIL || SUCCESS)
```

Le code est maintenant lisible.

Problème : 1 || 2 renvoit toujours 1.

J'imagine que tu voulais en fait faire 

```
(e === 1 || e === 2)
```

À clarifier donc !

**Comment by mathisang** [comment]
D'accord, en effet à comprendre du premier coup d'oeil ce n'est pas facile. Même moi j'ai eu du mal en revenant sur le code.
Mais au final, j'ai carrément enlever la condition, elle devait servir dans les toutes premières versions du jeu. Mais actuellement ce n'est plus utile.
Étant donné qu'on appelle cette fonction que si le bouton cliqué possède une conséquence, il renverra forcément 1 ou 2.

Merci !
https://github.com/mathisang/spaceGame/commit/ae3db7c6bc2ad99bb1f0e4ee07926f0f60cd2876
