### ISSUE TITLE
Extract CardButtons

### ISSUE THREAD

**Issue by bcalou** [mathisang/spaceGame#12]
Je vous invite à sortir CardButtons de RandomCards, qui est un fichier un peu long comparé aux autres, il aurait bien besoin d'être allégé

**Comment by mathisang** [comment]
J'ai sorti CardButtons ainsi que ContextCard, étant donné que lors de ma prochaine intégration je vais devoir y rajouter des choses cela évitera de trop surcharger le return.
Merci !
https://github.com/mathisang/spaceGame/commit/fbe3ac448a561a9dd8d453be533d296fcec8710d
