### ISSUE TITLE
Uniformize indentation

### ISSUE THREAD

**Issue by bcalou** [mathisang/spaceGame#2]
Votre indentation est incohérente d'un fichier à l'autre. 2 espaces, 4, 8, tabulations, c'est le bazar et ça va vous jouer des tours car ça fait du diff de commit pour rien.

Utilisez **2 espaces** et un outil comme Prettier (excellent) pour faire respecter ces règles communes.

Si vous êtes sur VSCode, activez le setting "format on save". Vous n'aurez plus qu'à passer sur chaque fichier, sauvegarder et le formattage se fera.

Ensuite faîtes un commit de formattage pour tout ça ;)

**Comment by mathisang** [comment]
Prettier configuré avec File Watchers, merci !

**Comment by bcalou** [comment]
Soyez vigilant : l'indentation est toujours un peu aléatoire.
Exemple EndCard, qui contient de l'intentation avec 2 et 4 espaces.

Normalement quand votre IDE est bien configuré, un coup de Ctrl+S formatte tout

**Comment by mathisang** [comment]
Mon IDE sur mon deuxième ordinateur n'étais pas bien configuré, en effet, ça a bouger l'indentation.
Merci, c'est bien réglé à la sauvegarde.
https://github.com/mathisang/spaceGame/commit/0e0e169c3818f70f653410e521bf2337ef291ce7
