### ISSUE TITLE
Improve JSON structure

### ISSUE THREAD

**Issue by bcalou** [mathisang/spaceGame#4]
Quelques problèmes à corriger dans la structure de randomCards.json

### 1

```
"text": {
      "reponse_un": "Faire l'espionnage",
      "reponse_deux": "Ne pas faire l'espionnage"
    },
```

Ici "reponse_un" n'est lié que par le nom de la clé à "reponse_un" dans la clé "value". C'est ce que j'appellerai un lien un lien faible. Pour avoir un JSON et un code JS plus propre, il faut un lien fort, exemple : 

```
"text": {
      "responses": [
         {
            "label": "Faire l'espionnage",
            "impacts": {
                 "argent": -10,
                 "recherche": 0,
                 "opinion": 0
            }
         },
         {
            "label": "Ne pas faire l'espionage",
            "impacts": {
                 "argent": 0,
                 "recherche": 0,
                 "opinion": 0
            }
         }
       ]
    },
```

Notez que j'ai utilisé un tableau pour rendre adaptable le nombre de réponses.

### 2

```
"consequence": {
      "exist": true,
```

La clé exist n'est pas utile, il vous suffit de ne pas mettre la clé consequence quand il n'y en a pas.

### 3

```
"consequence": {
      "button": "reponse_un",
```

Pareil que 1, c'est un lien faible, référencer une clé sous forme de string comme ça est trop instable.
Incluez directement success & fail dans les objets "responses".
Chaque response peut avoir une clé consequence, s'il y en a une, avec success & fail dedans.

**Comment by mathisang** [comment]
Structure mise à jour, merci !
