### ISSUE TITLE
Avoid nested ternaries

### ISSUE THREAD

**Issue by bcalou** [mathisang/spaceGame#7]
Une bonne pratique est d'éviter les ternaires imbriqués. Ils sont difficiles à lire au premier coup d'oeil.

```
totalJauge <= 120
      ? (avanceUsa = 2)
      : totalJauge >= 155
      ? (avanceUsa = 7)
      : (avanceUsa = 4);
```

Par ailleurs il serait plus clair / concis d'effectuer l'affectation en dehors du ternaire.

```
avanceUsa = totalJauge <= 120
      ? 2
      : totalJauge >= 155
      ? 7
      : 4;
```

Sans double ternaire : 

```
if (totalJauge <= 120) {
  avanceUsa = 2;
} else if (totalJauge => 155) {
  avanceUsa = 7;
} else {
  avanceUsa = 4;
}
```

Au final, j'ai enlevé tous les ternaires (alors que j'ai rien contre, bien au contraire). Dans cette situation le code ci-desus me semble le plus clair à lire !

**Comment by bcalou** [comment]
Ps : comme toujours, je prend un exemple de la codebase mais il peut y avoir plusieurs occurences

**Comment by bcalou** [comment]
Autre exemple d'un ternaire inutile : 

```
isSuccess
        ? updateGaugeConsequence(nextCard, numberResponse, "success")
        : updateGaugeConsequence(nextCard, numberResponse, "fail"
```

Beaucoup mieux ainsi : 
```
updateGaugeConsequence(nextCard, numberResponse, isSuccess ? "success" : "fail")
```

Serait encore mieux si la fonction prenait un booléen : 

```
updateGaugeConsequence(nextCard, numberResponse, isSuccess)
```

**Comment by mathisang** [comment]
Remarques et changements pris en compte, merci !
C'est vrai que j'ai du mal à optimiser mes ternaires du premier coup, je vais faire plus attention à rendre l'ensemble plus logique.
Je préfère ne pas attribuer de booléen sur la fonction, car ça me permet de parcourir plus facilement mon tableau par la suite.
Merci !
