### ISSUE TITLE
Improve seasons handling

### ISSUE THREAD

**Issue by bcalou** [mathisang/spaceGame#9]
N'est ce pas dommage d'avoir un fichier time.json de 250 lignes alors que vous pourriez avoir une fonction qui vous génère tout ça à la demande ?

Le déroulement est régulier, 4 saisons par an, les années s'incrémentent... Je suis sûr que vous pouvez trouver plus astucieux ;)

**Comment by mathisang** [comment]
En effet, c'était utile au début du projet pour tester rapidement.
Mais, maintenant c'est plus astucieux de faire autrement.
Merci !
https://github.com/mathisang/spaceGame/commit/56a44d102025505134129d567ee43122f80805d9
